const MenuItems= [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://static01.nyt.com/images/2016/06/15/dining/15PANCAKEGUIDE3-WEB/15PANCAKEGUIDE3-WEB-articleLarge.jpg',
      desc: `Indulge in a classic breakfast delight with our fluffy buttermilk pancakes. Served hot off the griddle, these golden, melt-in-your-mouth pancakes are a perfect balance of light and fluffy textures.`
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://www.kitchensanctuary.com/wp-content/uploads/2021/05/Double-Cheeseburger-square-FS-42.jpg',
      desc: `Prepare your taste buds for a burger experience like no other. Our double cheeseburger features two succulent beef patties, expertly seasoned and grilled to perfection.`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://www.thehungrybites.com/wp-content/uploads/2023/06/Strawberry-milkshake-frappuccino-featured.jpg',
      desc: `Dive into a world of sweetness with our luscious Strawberry Milkshake topped with a heavenly dollop of whipped cream, sprinkles, and more.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://huckleberrys.com/wp-content/uploads/2022/11/2eggs-Taters-Toast.jpg',
      desc: `Experience the ultimate breakfast comfort with our hearty dish of Eggs on Toast, served with a generous side of beans and cheese.  `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.theredheadbaker.com/wp-content/uploads/2017/05/french-bistro-burgers-4.jpg',
      desc: `Elevate your burger experience with our Eggcellent Burger, a delectable creation featuring a juicy, perfectly grilled beef patty crowned with a farm-fresh sunny-side-up egg and ripe, juicy tomato slices.  `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://houseofnasheats.com/wp-content/uploads/2023/01/Oreo-Milkshake-Square-1.jpg',
      desc: `This heavenly creation starts with velvety vanilla ice cream blended to creamy perfection, mingling with chunks of America's favorite cookie, Oreo.`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://recipes.net/wp-content/uploads/2023/05/hardees-bacon-egg-and-cheese-biscuit-recipe_b747d554c7d4b26588aceaf79683f1ac.jpeg',
      desc: `Start your day with a hearty and satisfying breakfast by indulging in our Bacon, Egg, and Cheese Biscuit Sandwich. `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/4/12/0/FNM_050118-Brie-Burgers-with-Fries_s4x3.jpg.rend.hgtvcom.616.462.suffix/1523547437873.jpeg',
      desc: `Dive into the ultimate classic comfort meal with our Cheeseburger and Fries Combo.Indulge in this classic duo for a satisfying and flavorful dining experience that will leave you craving more.  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://hips.hearstapps.com/hmg-prod/images/delish-220524-chocolate-milkshake-001-ab-web-1654180529.jpg?crop=0.647xw:0.972xh;0.177xw,0.0123xh&resize=1200:*',
      desc: `Whether you're cooling off on a hot day or simply satisfying your chocolate cravings, our Chocolate Milkshake is a delightful journey into the world of cocoa-infused bliss.`,
    },
  ];
  export default MenuItems;