"""empty message

Revision ID: 35d622a24340
Revises: 33ae378a44bf
Create Date: 2023-10-13 07:17:31.884205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d622a24340'
down_revision = '33ae378a44bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_liked_books_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_liked_books_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_liked_foods_food_id_foods')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_liked_foods_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], name=op.f('fk_liked_gifts_gift_id_gifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_liked_gifts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cartedbooks')
    op.drop_table('cartedgifts')
    op.drop_table('cartedfoods')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets_num', sa.Integer(), nullable=False))
        batch_op.drop_column('ticketsnum')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tickets_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tickets_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tickets_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tickets_event_id_events'), type_='foreignkey')
        batch_op.drop_column('event_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticketsnum', sa.INTEGER(), nullable=False))
        batch_op.drop_column('tickets_num')

    op.create_table('cartedfoods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartedgifts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartedbooks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('liked_gifts')
    op.drop_table('liked_foods')
    op.drop_table('liked_books')
    # ### end Alembic commands ###
