"""empty message

Revision ID: 40f91fb4279a
Revises: 35d622a24340
Create Date: 2023-10-13 09:57:56.999993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f91fb4279a'
down_revision = '35d622a24340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('tickets_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets_num', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
