"""empty message

Revision ID: 98e0cde62178
Revises: 40f91fb4279a
Create Date: 2023-10-18 10:54:54.515945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e0cde62178'
down_revision = '40f91fb4279a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_tickets', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('available_tickets')

    # ### end Alembic commands ###
